---
- name: Check Nginx container exist
  ansible.builtin.shell: |
    docker inspect {{ nginx_container_name }} | jq '. | length'
  register: this
  failed_when: this.stdout != "1"

- name: Check Nginx container is running
  ansible.builtin.shell: |
    docker inspect {{ nginx_container_name }} | jq -r '.[0].State.Status'
  register: this
  failed_when: this.stdout != "running"

- name: Check Nginx port is configured correctly
  ansible.builtin.shell: |
    docker inspect {{ nginx_container_name }} | jq -r '.[0].HostConfig.PortBindings | select(."80/tcp" != null) | ."80/tcp"[].HostPort'
  register: this
  failed_when: this.stdout != nginx_container_external_port

- name: Check connection
  ansible.builtin.uri:
    url: http://localhost:{{ nginx_container_external_port }}
    status_code: 200
    return_content: yes
